use std::env;
use std::fs;
use std::path::Path;

fn main() {
    generate_design_tokens();

    #[cfg(target_os = "windows")]
    {
        let mut res = winres::WindowsResource::new();
        res.set_icon("assets/icon.ico");
        res.compile().unwrap();
    }
}

/// Parse theme/tokens.toml and emit $OUT_DIR/design_tokens.rs with the
/// compile-time constants consumed by src/theme.rs. Keeping the design tokens
/// in one TOML file makes the palette/scale the single source of truth.
fn generate_design_tokens() {
    println!("cargo:rerun-if-changed=theme/tokens.toml");

    let src = fs::read_to_string("theme/tokens.toml").expect("read theme/tokens.toml");
    let t: toml::Table = src.parse().expect("parse theme/tokens.toml");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from design/tokens.toml — DO NOT EDIT.\n\n");

    // -- Solid colors (token key -> theme.rs const name) --------------------
    let solid: &[(&str, &str)] = &[
        ("bg", "BLUE_BG"),
        ("bg_2", "BLUE_MID"),
        ("tile_top", "BLUE_DARK"),
        ("tile_bottom", "TILE_BOTTOM"),
        ("tile_flat", "TILE_FLAT"),
        ("ink", "WHITE"),
        ("ink_dim", "INK_DIM"),
        ("accent", "GOLD"),
        ("accent_2", "GOLD_HOVER"),
        ("good", "GREEN_CORRECT"),
        ("bad", "RED_WRONG"),
        ("on_accent", "ON_ACCENT"),
        ("body_bg", "BODY_BG"),
        ("app_top", "APP_TOP"),
        ("app_mid", "APP_MID"),
        ("app_bottom", "APP_BOTTOM"),
    ];
    let color = t["color"].as_table().expect("[color] table");
    out.push_str("// Solid palette\n");
    for (key, name) in solid {
        let hex = color[*key].as_str().unwrap_or_else(|| panic!("color.{key} string"));
        let (r, g, b) = parse_hex(hex);
        out.push_str(&format!(
            "pub const {name}: egui::Color32 = egui::Color32::from_rgb({r}, {g}, {b});\n"
        ));
    }

    // -- Alpha-composited colors -> premultiplied --------------------------
    let alpha: &[(&str, &str)] = &[
        ("accent_soft", "ACCENT_SOFT"),
        ("line", "LINE"),
        ("correct_bg", "CORRECT_BG"),
        ("wrong_bg", "WRONG_BG"),
    ];
    let ca = t["color_alpha"].as_table().expect("[color_alpha] table");
    out.push_str("\n// Alpha-composited (stored premultiplied)\n");
    for (key, name) in alpha {
        let item = ca[*key].as_table().unwrap_or_else(|| panic!("color_alpha.{key}"));
        let (r, g, b) = parse_hex(item["base"].as_str().expect("base"));
        let a = item["alpha"].as_float().expect("alpha") as f32;
        let pr = (r as f32 * a).round() as u8;
        let pg = (g as f32 * a).round() as u8;
        let pb = (b as f32 * a).round() as u8;
        let pa = (a * 255.0).round() as u8;
        out.push_str(&format!(
            "pub const {name}: egui::Color32 = \
             egui::Color32::from_rgba_premultiplied({pr}, {pg}, {pb}, {pa});\n"
        ));
    }

    // -- f32 scalar sections (radius / spacing / type) ----------------------
    emit_f32(&mut out, &t, "radius", "RADIUS", "// Corner radii");
    emit_f32(&mut out, &t, "spacing", "SPACE", "// Spacing");
    emit_f32(&mut out, &t, "type", "TYPE", "// Type scale");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("design_tokens.rs");
    fs::write(dest, out).expect("write design_tokens.rs");
}

/// Emit every f32 value in `[section]` as `pub const {PREFIX}_{KEY}: f32`.
fn emit_f32(out: &mut String, t: &toml::Table, section: &str, prefix: &str, header: &str) {
    let table = t[section]
        .as_table()
        .unwrap_or_else(|| panic!("[{section}] table"));
    out.push_str(&format!("\n{header}\n"));
    for (key, val) in table {
        let v = val
            .as_float()
            .or_else(|| val.as_integer().map(|i| i as f64))
            .unwrap_or_else(|| panic!("{section}.{key} number"));
        let name = format!("{}_{}", prefix, key.to_uppercase());
        out.push_str(&format!("pub const {name}: f32 = {v:?};\n"));
    }
}

/// "#rrggbb" -> (r, g, b).
fn parse_hex(hex: &str) -> (u8, u8, u8) {
    let h = hex.trim_start_matches('#');
    assert_eq!(h.len(), 6, "expected #rrggbb, got {hex}");
    let r = u8::from_str_radix(&h[0..2], 16).unwrap();
    let g = u8::from_str_radix(&h[2..4], 16).unwrap();
    let b = u8::from_str_radix(&h[4..6], 16).unwrap();
    (r, g, b)
}
